const KEY='ritm_personal_v1';
const seed={clients:[{id:1,name:'Анна Петрова',phone:'+7 900 123-45-67',note:'Подготовка к экзамену',package:'8 занятий',remaining:3,price:7200,status:'active'},{id:2,name:'Максим Иванов',phone:'+7 901 555-20-10',note:'Индивидуальные занятия',package:'12 занятий',remaining:8,price:10800,status:'active'},{id:3,name:'София Ким',phone:'+7 902 111-22-33',note:'',package:'4 занятия',remaining:1,price:4200,status:'ending'}],lessons:[{id:1,date:'2026-10-06',time:'17:00',clientId:1,type:'Индивидуальное',status:'planned'},{id:2,date:'2026-10-06',time:'18:30',clientId:2,type:'Индивидуальное',status:'planned'},{id:3,date:'2026-10-07',time:'16:00',clientId:3,type:'Индивидуальное',status:'planned'}],payments:[{id:1,clientId:1,amount:7200,date:'2026-10-01',status:'paid'},{id:2,clientId:2,amount:10800,date:'2026-09-28',status:'paid'}],settings:{name:'Егор',specialistMode:true}};
let db=JSON.parse(localStorage.getItem(KEY)||'null')||seed; const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let page='dashboard';
const fmt=n=>new Intl.NumberFormat('ru-RU').format(n)+' ₽';
const dateFmt=s=>new Date(s+'T00:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'});
const client=id=>db.clients.find(c=>c.id==id);
function nav(){ $$('#nav button,.sidebar-bottom button').forEach(b=>b.classList.toggle('active',b.dataset.page===page)); }
function title(){let t={dashboard:'Главная',schedule:'Расписание',clients:'Клиенты',subscriptions:'Абонементы',payments:'Оплаты',settings:'Настройки'}[page];$('#pageTitle').textContent=t;$('#todayLabel').textContent=new Date().toLocaleDateString('ru-RU',{weekday:'long',day:'numeric',month:'long'});}
function render(){nav();title(); ({dashboard, schedule, clients, subscriptions, payments, settings}[page])();}
function dashboard(){let today='2026-10-06', lessons=db.lessons.filter(x=>x.date===today).sort((a,b)=>a.time.localeCompare(b.time)); let income=db.payments.filter(x=>x.status==='paid'&&x.date.startsWith('2026-10')).reduce((a,x)=>a+x.amount,0); $('#content').innerHTML=`<div class="cards"><div class="stat"><div class="label">Занятий сегодня</div><div class="value">${lessons.length}</div><div class="hint">на ${dateFmt(today)}</div></div><div class="stat"><div class="label">Клиенты</div><div class="value">${db.clients.length}</div><div class="hint">активных ${db.clients.filter(x=>x.status==='active').length}</div></div><div class="stat"><div class="label">Доход за месяц</div><div class="value">${fmt(income)}</div><div class="hint">по отмеченным оплатам</div></div><div class="stat"><div class="label">Требуют внимания</div><div class="value">${db.clients.filter(x=>x.remaining<=2).length}</div><div class="hint">абонементы заканчиваются</div></div></div><div class="content-grid"><div class="panel"><div class="section-head"><h3>Сегодня</h3><button class="link-btn" onclick="setPage('schedule')">Всё расписание →</button></div>${lessons.length?lessons.map(l=>`<div class="event"><div class="time">${l.time}</div><div><div class="event-title">${client(l.clientId)?.name||'Клиент удалён'}</div><div class="event-sub">${l.type} · <span class="pill">${l.status==='planned'?'Запланировано':'Проведено'}</span></div></div></div>`).join(''):'<div class="empty">Сегодня занятий нет</div>'}</div><div class="panel"><div class="section-head"><h3>Требует внимания</h3><button class="link-btn" onclick="setPage('subscriptions')">Все →</button></div>${db.clients.filter(c=>c.remaining<=2).map(c=>`<div class="attention"><div><strong>${c.name}</strong><small>Осталось ${c.remaining} ${c.remaining===1?'занятие':'занятия'}</small></div><span class="status warn">Продлить</span></div>`).join('')||'<div class="empty">Всё в порядке</div>'}</div></div>`}
function schedule(){let base=new Date('2026-10-06T00:00:00');let days=[...Array(7)].map((_,i)=>{let d=new Date(base);d.setDate(base.getDate()+i);return d});$('#content').innerHTML=`<div class="calendar-head"><div><button onclick="shiftWeek(-1)">←</button> <button onclick="shiftWeek(1)">→</button></div><button class="primary" onclick="openLesson()">＋ Занятие</button></div><div class="week">${days.map(d=>{let ds=d.toISOString().slice(0,10), ls=db.lessons.filter(x=>x.date===ds).sort((a,b)=>a.time.localeCompare(b.time));return `<div class="day"><div class="day-head">${d.toLocaleDateString('ru-RU',{weekday:'short'})}<b>${d.getDate()}</b></div>${ls.map(l=>`<div class="slot" onclick="openLesson(${l.id})"><b>${l.time}</b>${client(l.clientId)?.name||'—'}<br><span class="muted">${l.type}</span></div>`).join('')||'<div class="muted" style="font-size:11px">Свободно</div>'}</div>`}).join('')}</div>`}
function clients(){let rows=db.clients.map(c=>`<tr><td class="person">${c.name}</td><td>${c.phone||'—'}</td><td>${c.package}</td><td>${c.remaining}</td><td><span class="status ${c.remaining>2?'good':'warn'}">${c.remaining>2?'Активен':'Заканчивается'}</span></td><td><button class="link-btn" onclick="openClient(${c.id})">Открыть</button></td></tr>`).join('');$('#content').innerHTML=`<div class="toolbar"><input class="search" id="clientSearch" placeholder="Поиск клиента…" oninput="filterClients()"><button class="primary" onclick="openClient()">＋ Добавить клиента</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Клиент</th><th>Телефон</th><th>Абонемент</th><th>Осталось</th><th>Статус</th><th></th></tr></thead><tbody id="clientRows">${rows}</tbody></table></div>`}
function filterClients(){let q=$('#clientSearch').value.toLowerCase();$$('#clientRows tr').forEach(r=>r.style.display=r.textContent.toLowerCase().includes(q)?'':'none')}
function subscriptions(){let rows=db.clients.map(c=>`<tr><td class="person">${c.name}</td><td>${c.package}</td><td>${c.remaining}</td><td>${fmt(c.price)}</td><td>${c.remaining<=2?'<span class="status warn">Продлить</span>':'<span class="status good">Активен</span>'}</td><td><button class="link-btn" onclick="openClient(${c.id})">Изменить</button></td></tr>`).join('');$('#content').innerHTML=`<div class="toolbar"><div class="muted" style="font-size:13px">Остаток занятий и стоимость по каждому клиенту</div><button class="primary" onclick="openClient()">＋ Новый абонемент</button></div><div class="table-wrap"><table class="table"><thead><tr><th>Клиент</th><th>Пакет</th><th>Осталось</th><th>Стоимость</th><th>Статус</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>`}
function payments(){let rows=db.payments.slice().reverse().map(p=>`<tr><td class="person">${client(p.clientId)?.name||'—'}</td><td>${dateFmt(p.date)}</td><td>${fmt(p.amount)}</td><td><span class="status good">Оплачено</span></td></tr>`).join('');let total=db.payments.reduce((a,p)=>a+p.amount,0);$('#content').innerHTML=`<div class="cards" style="margin-top:24px"><div class="stat"><div class="label">Всего отмечено</div><div class="value">${fmt(total)}</div><div class="hint">за всё время</div></div><div class="stat"><div class="label">Оплат</div><div class="value">${db.payments.length}</div><div class="hint">операций</div></div></div><div class="table-wrap"><table class="table"><thead><tr><th>Клиент</th><th>Дата</th><th>Сумма</th><th>Статус</th></tr></thead><tbody>${rows}</tbody></table></div>`}
function settings(){ $('#content').innerHTML=`<div class="settings-grid"><div class="setting"><h3>Профиль</h3><p>Имя отображается в личном интерфейсе.</p><div class="form"><label>Имя<input id="setName" value="${db.settings.name||''}"></label><button class="primary" onclick="saveSettings()">Сохранить</button></div></div><div class="setting"><h3>Режим</h3><p>Можно использовать приложение как учётную систему для занятий или как CRM для клиентов.</p><div class="toggle"><span style="font-size:13px">Язык терминов: клиенты / занятия</span><input id="mode" type="checkbox" ${db.settings.specialistMode?'checked':''} onchange="saveSettings()"></div></div><div class="setting"><h3>Данные</h3><p>В этой версии всё хранится локально в браузере. Можно сделать резервную копию JSON и восстановить её позже.</p><button class="secondary" onclick="exportData()">Экспортировать данные</button> <button class="secondary" onclick="resetData()">Сбросить</button></div><div class="setting"><h3>Telegram</h3><p>Подключение бота вынесено в следующий этап. Здесь можно будет указать токен и шаблоны уведомлений.</p><span class="pill">Скоро</span></div></div>`}
function saveSettings(){db.settings.name=$('#setName')?.value||db.settings.name;db.settings.specialistMode=$('#mode')?.checked??db.settings.specialistMode;save();render()}
function openClient(id){let c=id?client(id):{name:'',phone:'',note:'',package:'8 занятий',remaining:8,price:7200};openModal(id?'Редактировать клиента':'Новый клиент',`<div class="form"><label>Имя<input id="fName" value="${c.name}"></label><label>Телефон<input id="fPhone" value="${c.phone||''}"></label><label>Абонемент<input id="fPackage" value="${c.package||''}"></label><label>Осталось занятий<input id="fRemain" type="number" min="0" value="${c.remaining??0}"></label><label>Стоимость<input id="fPrice" type="number" min="0" value="${c.price||0}"></label><label>Заметка<textarea id="fNote">${c.note||''}</textarea></label><div class="form-actions"><button class="secondary" onclick="closeModal()">Отмена</button><button class="primary" onclick="saveClient(${id||'null'})">Сохранить</button></div></div>`)}
function saveClient(id){let c={name:$('#fName').value.trim(),phone:$('#fPhone').value,package:$('#fPackage').value,remaining:+$('#fRemain').value||0,price:+$('#fPrice').value||0,note:$('#fNote').value,status:(+$('#fRemain').value||0)>2?'active':'ending'};if(!c.name)return alert('Укажите имя');if(id){Object.assign(client(id),c)}else{c.id=Date.now();db.clients.push(c)}save();closeModal();render()}
function openLesson(id){let l=id?db.lessons.find(x=>x.id==id):{date:'2026-10-06',time:'17:00',clientId:db.clients[0]?.id||'',type:'Индивидуальное',status:'planned'};openModal(id?'Редактировать занятие':'Новое занятие',`<div class="form"><label>Клиент<select id="lClient">${db.clients.map(c=>`<option value="${c.id}" ${c.id==l.clientId?'selected':''}>${c.name}</option>`).join('')}</select></label><label>Дата<input id="lDate" type="date" value="${l.date}"></label><label>Время<input id="lTime" type="time" value="${l.time}"></label><label>Формат<select id="lType"><option ${l.type==='Индивидуальное'?'selected':''}>Индивидуальное</option><option ${l.type==='Парное'?'selected':''}>Парное</option><option ${l.type==='Групповое'?'selected':''}>Групповое</option></select></label><label>Статус<select id="lStatus"><option value="planned" ${l.status==='planned'?'selected':''}>Запланировано</option><option value="done" ${l.status==='done'?'selected':''}>Проведено</option><option value="cancelled" ${l.status==='cancelled'?'selected':''}>Отменено</option></select></label><div class="form-actions"><button class="secondary" onclick="closeModal()">Отмена</button><button class="primary" onclick="saveLesson(${id||'null'})">Сохранить</button></div></div>`)}
function saveLesson(id){let l={id:id||Date.now(),clientId:+$('#lClient').value,date:$('#lDate').value,time:$('#lTime').value,type:$('#lType').value,status:$('#lStatus').value};if(id)Object.assign(db.lessons.find(x=>x.id==id),l);else db.lessons.push(l);save();closeModal();render()}
function openModal(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').classList.add('open')}function closeModal(){$('#modal').classList.remove('open')}
function setPage(p){page=p;render()}function exportData(){let blob=new Blob([JSON.stringify(db,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='ritm-backup.json';a.click()}function resetData(){if(confirm('Удалить все локальные данные и вернуть демо-данные?')){db=JSON.parse(JSON.stringify(seed));save();render()}}
$('#nav').addEventListener('click',e=>{let b=e.target.closest('button[data-page]');if(b)setPage(b.dataset.page)});$('.sidebar-bottom').addEventListener('click',e=>{let b=e.target.closest('button[data-page]');if(b)setPage(b.dataset.page)});$('#addBtn').onclick=()=>page==='schedule'?openLesson():openClient();$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};
render();
